### PR TITLE
Added more improvements about this plone theme package

### PR DESCRIPTION
**Pull request by macagua**
Hi @gyst please, can you check these improvements and if all are Ok, can merged it?

### CODE REVIEW

**Comment by gyst** [comment]
Sorry, I missed this in my email backlog. How about we move this package into the collective? I even forgot I wrote it....

**Review by gyst — APPROVED** [review]

**Comment by macagua** [comment]
@gyst thanks!

It's a great idea to move it into collecte, :+1: , just a request, bejfore to move it into collective, please change the repo description for "Transition Theme, is an installable Diazo theme for Plone 4 using the transition template" and set the following topics "plone4x, diazo, plonetheme transition, theme", please!

**Comment by macagua** [comment]
@gyst really thanks for this merge! ;-)

**Comment by gyst** [comment]
@macagua I moved this into `collective` and gave you owner rights on the Pypi package.

**Comment by macagua** [comment]
Thanks @gyst 

For *Transfer Ownership*

"Transferring repository ownership to Collective
How to move your repository under Collective shared ownership. About transfering the ownership of repositories see GitHub instructions regarding transfers. You can do this yourself with GitHub's *Transfer Ownership* button 'if the repository belongs to your personal account.

For repositories part of any GitHub organization (and organization only) you need the organization admin permissions to perform the transfer. Admin in the third party organization must be also collective member."

https://collective.github.io

**Pull request merged**
